Каташинский Кирилл WEB-21
kirill555101/go-hw-1 pull request #1
Opened 2022-02-11 20:05 UTC by kirill555101

2022-02-21 20:12 UTC, BoldinDmitry requested changes

2022-02-21 20:12 UTC, BoldinDmitry commented on part1/uniq/uniq.go
> +func show(options *Options, result *[]string, str string, repeats int) {
можно писать без звездочек, ответ вот туть: https://stackoverflow.com/questions/39993688/are-slices-passed-by-value

2022-02-21 20:12 UTC, BoldinDmitry commented on part1/main.go
> +	"./uniq"
лучше сделать его main'ом внутри пакета uniq

2022-02-21 20:12 UTC, BoldinDmitry commented on part1/uniq_test.go
> +func TestDefaultSuccess(t *testing.T) {
Если есть много тестов, в которых одна логика, но просто разные значения, то лучший способ -- это табличные тесты
Сможешь на них переписать?

2022-02-21 20:12 UTC, BoldinDmitry commented on part2/calc_test.go
> +func TestAddSuccess(t *testing.T) {
Здесь тоже можешь на табличные переписать, плз?

2022-02-21 20:12 UTC, BoldinDmitry commented on part2/calc_test.go
> +	"./calc"
Лучше постараться без такого, чтобы тесты лежали в директории, где находится код, который мы тестируем

2022-02-23 20:30 UTC, BoldinDmitry approved these changes

2022-02-28 13:13 UTC, ksenobait09 commented on part1/main.go
> +		PrintUsage()
кажется тут нужно прекратить работу

2022-02-28 13:14 UTC, ksenobait09 commented on part1/main.go
> +		fmt.Println(err)
и что за ошибка выведеться, если err будет nil?

2022-02-28 13:15 UTC, ksenobait09 commented on part1/uniq.go
> +	c bool
Давай дадим человекочитаемые названия опциям)

2022-02-28 13:24 UTC, ksenobait09 commented on part1/uniq.go
> +func (options *Options) ResetParams() {
не понял, а зачем это?

2022-02-28 14:10 UTC, ksenobait09 commented on part1/uniq.go
> +		if !options.c && options.u && options.d {
не понял, а как может быть одновременно U и D? это же взаимоисключающие параметры

2022-02-28 14:14 UTC, ksenobait09 commented on part1/uniq.go
> +			show(options, &result, text[index-1], repeats)
1) не нравится, что функа show вызывается по условию и в тоже время внутри себя проверяет эти же условия. 
2) функа называется show - показать, что не очень отвечает на вопрос что она делает: "добавляет в массив"

2022-02-28 14:21 UTC, ksenobait09 commented on part2/calc.go
> +	len := len(stack.buff)
дальше по коду этой функции, функция len будет недоступна, ты ее заоверрайдил

2022-09-20 08:02 UTC, merged